### ISSUE TITLE
Vite 5 Support

### ISSUE THREAD

**Issue by malikdoksoz** [defstudio/vite-livewire-plugin#95]
Is there any work on Vite 5 support? Otherwise I can open a pull request.

**Comment by fabio-ivona** [comment]
Hi! I was planning starting this soon, but any PR will be welcome, thanks!

**Comment by namumakwembo** [comment]
When can we get support for Vite 5 ?

**Comment by BALOTIAS** [comment]
Created a PR now @fabio-ivona .. hope it helps :))

**Comment by fabio-ivona** [comment]
Released :heart:
